env = Environment()

env['APP_TARGET'] = 'MarionetteZooApp'
env['APP_SOURCES'] = ['Audio.cpp', 'BulletDebugDrawer.cpp', 'BulletPicker.cpp',
					'BulletExtension/btSoftWorldImporter.cpp',
					'MarionetteZooApp.cpp', 'ModelFileManager.cpp',
					'BulletParameter.cpp', 'BulletWorld.cpp',
					'Model.cpp', 'ModelManager.cpp']

env['ASSETS'] = ['models/*']

env['DEBUG'] = 1

env = SConscript('../../../blocks/MndlKit/scons/SConscript', exports = 'env')
env = SConscript('../../../blocks/Cinder-Assimp/scons/SConscript', exports = 'env')
env = SConscript('../../../blocks/Cinder-Bullet/scons/SConscript', exports = 'env')
env = SConscript('../../../blocks/Cinder-OpenAL/scons/SConscript', exports = 'env')

SConscript('../../../scons/SConscript', exports = 'env')
