env = Environment()

env['APP_TARGET'] = 'MarionetteZooApp'
env['APP_SOURCES'] = ['BulletDebugDrawer.cpp', 'BulletPicker.cpp',
					'MarionetteZooApp.cpp', 'ModelFileManager.cpp',
					'BulletParameter.cpp', 'BulletWorld.cpp',
					'Model.cpp', 'ModelManager.cpp']

env['ASSETS'] = ['tomi1.jpg', 'bird.dae', 'bird.xml']
env['DEBUG'] = 0

env = SConscript('../../../blocks/MndlKit/scons/SConscript', exports = 'env')
env = SConscript('../../../blocks/Cinder-Assimp/scons/SConscript', exports = 'env')
env = SConscript('../../../blocks/Cinder-Bullet/scons/SConscript', exports = 'env')

SConscript('../../../scons/SConscript', exports = 'env')
